# Creates the StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: validation-sc
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: TargetResourceLimits:
        value: |-
            memory: 1Gi
            cpu: 200m
      - name: AuxResourceLimits
        value: |-
            memory: 0.5Gi
            cpu: 50m
provisioner: openebs.io/provisioner-iscsi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: validation-pvc
  namespace: validation-ns
  labels:
    name: validation-pvc
spec:
  storageClassName: validation-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
